#!/bin/bash

sudo apt update -y
#installation of jenkins

sudo wget -O /usr/share/keyrings/jenkins-keyring.asc \
  https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
echo "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc]" \
  https://pkg.jenkins.io/debian-stable binary/ | sudo tee \
  /etc/apt/sources.list.d/jenkins.list > /dev/null
sudo apt-get update
sudo apt-get install jenkins


if [ $? -eq 0 ]; then
    echo "Jenkins is installed"
else
    echo "Jenkins is not installed"
fi

#installation of docker

sudo apt install docker.io

if [ $? -eq 0 ]; then
    echo "docker  is installed"
else
    echo "docker is not installed"
fi


#installation of jdk 17
sudo apt install openjdk-17-jdk openjdk-17-jre


if [ $? -eq 0 ]; then
    echo "docker,jenkins,java  is installed"
else
    echo "jdk  is not installed"
fi
#installation of maven
sudo apt install maven -y

if [ $? -eq 0 ]; then
    echo "docker,jenkins,java,maven  is installed"
else
    echo "maven  is not installed"
fi

#installation of ansible


 sudo apt install software-properties-common
 sudo add-apt-repository --yes --update ppa:ansible/ansible
 sudo apt install ansible -y

 if [ $? -eq 0 ]; then
    echo "docker,jenkins,java,maven,ansible   is installed"
else
    echo "ansible  is not installed"
fi




                                    
