#!/bin/bash

# download tomat 9
wget https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.88/bin/apache-tomcat-9.0.88.tar.gz

#untar the file
tar xvfz apache-tomcat-9.0.88.tar.gz


# copy file to tomat int /opt/tomcat

mv apache-tomcat-9.0.88   /opt/tomcat


#start tomcat 
 cd /opt/tomcat/bin


 chmod +x .*sh


 ./startup.sh








 
